mybatis:
  configuration:
    map-underscore-to-camel-case: true
  congiguration:
    default-feth-size: 100
    default-statement-timeout: 3000
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.seckill.agent.entity
redis:
  host: 127.0.0.1
  password: 123456
  poolMaxTotal: 8
  poolMaxWait: 1000
  poolMaxdle: 8
  port: 6379
  timeout: 6
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    initialSize: 1
    maxActive: 3
    maxOpenPreparedStatements: 20
    minEvictableldleTimeMillis: 30000
    password: 123456
    poolPreparedStatements: true
    testOnBrrow: false
    testOnReturn: false
    testWhiledle: true
    timeBetweenEvictionRunMillis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/seckill?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8&generateSimpleParameterMetadata=true&autoReconnect=true&useSSL=false&serverTimezone=GMT%2b8&allowMultiQueries=true
    username: root
    validationQuery: select 'x'
  thymeleaf:
    cache: false
    content-type: text/html
    enable: true
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
  thymelesf:
    mode: html5

### 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
  ### xxl.job.admin.addresses=http://127.0.0.1:8080/xxl-job-admin
  ### 执行器通讯TOKEN [选填]：非空时启用；
  ### xxl.job.accessToken=
  ### 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
  ### xxl.job.executor.appname=springboot-xxl-executor
  ### 执行器注册 [选填]：优先使用该配置作为注册地址，为空时使用内嵌服务 ”IP:PORT“ 作为注册地址。从而更灵活的支持容器类型执行器动态IP和动态映射端口问题。
  ### xxl.job.executor.address=
  ### 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
  ### xxl.job.executor.ip=
  ### 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
  ### xxl.job.executor.port=9999
  ### 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
  ### xxl.job.executor.logpath=/data/applogs/xxl-job/jobhandler
  ### 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
  ### xxl.job.executor.logretentiondays=30


xxl:
  job:
    accessToken: ''
    admin:
      addresses: http://127.0.0.1:8088/xxl-job-admin
    executor:
      address: ''
      appname: xxl-job-executor-sample
      ip: ''
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 9999

