mybatis:
  configuration:
    map-underscore-to-camel-case: true
  congiguration:
    default-feth-size: 100
    default-statement-timeout: 3000
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.miaosha.agent.entity
redis:
  host: 127.0.0.1
  password: 123456
  poolMaxTotal: 8
  poolMaxWait: 1000
  poolMaxdle: 8
  port: 6379
  timeout: 6
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    initialSize: 1
    maxActive: 3
    maxOpenPreparedStatements: 20
    minEvictableldleTimeMillis: 30000
    password: 123456
    poolPreparedStatements: true
    testOnBrrow: false
    testOnReturn: false
    testWhiledle: true
    timeBetweenEvictionRunMillis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/miaosha?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8&generateSimpleParameterMetadata=true&autoReconnect=true&useSSL=false&serverTimezone=GMT%2b8&allowMultiQueries=true
    username: root
    validationQuery: select 'x'
  thymeleaf:
    cache: false
    content-type: text/html
    enable: true
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
  thymelesf:
    mode: html5
